# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160727175031 on 2016-08-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='regions',
            field=models.ManyToManyField(to='app.Region'),
        ),
        migrations.AddField(
            model_name='client',
            name='regions',
            field=models.ManyToManyField(to='app.Region'),
        ),
    ]
